### ISSUE TITLE
Bheithir versions from 0.7 onwards do not work

### ISSUE THREAD

**Issue by Chocolateunu** [MechaDragonX/Bheithir#10]
Hello!

Since the 3 recent versions of Bheithir were uploaded, all three I have not been able to open. I have .NET 5.0 installed, but that doesn't fix the problem. If before I had a mishap and a black window appeared in an instant, now it is not even able to appear something. I have no idea if it's my problem, but version 0.6 still works for me, but the current 3 don't :/

**Comment by MechaDragonX** [comment]
Just writing to let you know I've seen the issue and I will test it soon. I'll have to use a VM or something since I haven't tested it outside my computer. That will take some time and I'm busy with school right now.

I'll keep you posted, but I should be able to work on this in a couple days. Sorry about the delay.

It's a good thing the emulators supported are completely portable, so transferring them from one computer to another will be easy lol

**Comment by MechaDragonX** [comment]
I think the program isn't working because of something I failed to communicate. Are you opening the emulator, and then running Bheithir? That's the way it works. Otherwise it tells you that the specified emulator isn't open and the program closes, or simply ends if you're running from the command line.

**Comment by MechaDragonX** [comment]
I ran into issues installing .NET Framework 4.5.2 on a Windows 7 VM (.NET 4.5 is a preq for Discord), so I wasn't able to completely test it, but running the program without having Discord open works as expected.

The program never checks if Discord is present and open, it simply communicates to Discord's servers to set the presence status.

**Comment by Chocolateunu** [comment]
I just tried to run it with the emulator open and it doesn't work, then I did the same with discord closed and nothing happens either

**Comment by MechaDragonX** [comment]
Can you run it via the command line and then take a screenshot of what you see? The program just closes automatically if it ends normally or prematurely. (I have to fix that...) Running it via the command line bypasses that since it's not creating a window or anything.

**Comment by Chocolateunu** [comment]
Sorry, but I don't know how to do that. Can you explain how to do it?

**Comment by MechaDragonX** [comment]
Sure!

For these instructions, using Command Prompt (CMD) or PowerShell (PS) works, but because CMD is outdated, I'll show PS. I lso assume you are using Windows 10, but the instructions are very similar on Windows 8.1 and 7.

1. Open PowerShell.
    ![How To Open PS](https://i.imgur.com/aS8XuJJ.gif "How to Open PS")
    Once you do, you should see a prompt that looks like this, but with your username:
    ```
    PS C:\Users\ragha>  
    ```
    From here out, anything you need to type outside Bheithir will be written like this:
    ```
    >  <command>
    ```
2. Next, you need to navigate to the folder where you downloaded Bheithir. The easier way is as follows:
    a. Open the folder where Bheithir is saved in File Explorer
    b. Copy the path to the folder:
    ![Copying Path](https://i.imgur.com/zoZwMsM.gif "Copying Path")
    c. Type this into PS:
    ```
    > cd '<path>'
    ```
    Example:
    ```ps
    > cd 'C:\Users\ragha\Documents\GitHub\Bheithir\bin\Debug\net5.0'
    ```
    *Note: `'` are not required if the path has no spaces. Spaces denote different arguments, so you need quotation marks if you want to go to folder whose path has spaces.*
    Screenshot from within PS:
    ![PS Folder Change](https://user-images.githubusercontent.com/23585932/116761120-9f3d9300-a9cb-11eb-80f6-60a533c32c80.png "PS Folder Change")
3. Type:
    ```ps
    > .\Bheithir.exe
    ```
    This will run the program:
    ![Running from PS](https://user-images.githubusercontent.com/23585932/116761246-f93e5880-a9cb-11eb-8729-f345844824bb.png "Running from PS")
    *Note: I fixed a bug today where the program would actually crash after displaying that message, so it will not look the same.*
4. Now follow the instructions in the program as you have been before. Because you are running the program from the command line, instead of clicking on the EXE, the window won't close. That will give you time to take a screenshot so I can see what's going on.
5. Taking a screenshot
    a. Windows 10
        i. Press `Windows`+`Shift`+`S` to open "Snip & Sketch"
        ii. Do what you see here:
        ![Snip & Sketch Instructions](https://i.imgur.com/WoyQjaT.gif "Snip & Sketch Instructions")
        iii. Now what you have will be on your clipboard, which means you can copy and paste it into a comment here.
    b. Windows 7 and up
        i. Open "Snipping Tool"
        ![Opening Snipping Tool](https://i.imgur.com/tLZnBpq.gif "Opening Snipping Tool")
        ii. Do what you see here:
        ![Snipping Tool Instructions](https://i.imgur.com/ez5F65r.gif "Snipping Tool Instructions")
        iii. Now what you have will be on your clipboard, which means you can copy and paste it into a comment here.

Sorry if you already knew how to do some of the things here. I just wanted to be thorough in case you didn't. And, I hope that helps!

**Comment by Chocolateunu** [comment]
![screenshot1](https://user-images.githubusercontent.com/69604481/116763482-86dd7080-a9eb-11eb-947e-82f844cf8aea.png)
This is how far I can go :/

**Comment by MechaDragonX** [comment]
In between v0.6 and v0.7, .NET 5 came out, so I switched to that. I was previously using .NET Core 3.1, which you probably had installed if the previous versions work. Download .NET 5 [here](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.5-windows-x86-installer). I was gonna make builds where you didn't need to install .NET, but that meant there'd be a million `*.dll` files, so I dropped it.

Sorry for not making the framework change clear in the release notes.

**Comment by Chocolateunu** [comment]
I already had that program installed, but it was the x64 version 😓.
Sorry for the inconvenience :(

**Comment by MechaDragonX** [comment]
If you have a 64-bit computer, you can run the x86 and x64 version, but if you have a 32-bit computer, you can only run the x86 version. That's why I only make x86 builds of Bheithir. There are reasons to target 64-bit, but those reasons aren't important for this.

And no worries!
